name: Test Self Hosted

on: [push]

jobs:
  RunSelfHosted:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: self-hosted

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: MacOS Signing
      run: |
        openssl enc -aes-256-cbc -a -d -in ./release_script/mac_only/Certificates.p12.enc -out ./release_script/mac_only/Certificates.p12 -k $MAC_DECRYPT_KEY
        md5 ./release_script/mac_only/Certificates.p12
        bash release_script/mac_only/add-osx-cert.sh
      env:
        MAC_DECRYPT_KEY: ${{ secrets.MAC_DECRYPT_KEY }}
    - name: Processing MacOS
      run: |
        mkdir $GITHUB_WORKSPACE/temp
        cd $GITHUB_WORKSPACE/temp
        curl -O -L --insecure https://download.processing.org/processing-3.5.3-macosx.zip
        unzip processing-3.5.3-macosx.zip
        echo ${GITHUB_WORKSPACE}/release_script/mac_only>>$GITHUB_PATH
        chmod +x $GITHUB_WORKSPACE/release_script/mac_only/processing-java
        mkdir -p ~/Documents/Processing/libraries/
        cp -a $GITHUB_WORKSPACE/OpenBCI_GUI/libraries/ ~/Documents/Processing/libraries/
        mkdir -p ~/sketchbook/libraries/
        cp -a $GITHUB_WORKSPACE/OpenBCI_GUI/libraries/ ~/sketchbook/libraries/
        echo ~/sketchbook/libraries/
        ls ~/sketchbook/libraries/
    - name: Run Make Release Script
      run: |
        cd $GITHUB_WORKSPACE
        python3 $GITHUB_WORKSPACE/release_script/make-release.py --no-prompts
        GUI_COMMIT_TIME=`cat temp/timestamp.txt`
        GUI_VERSION_STRING=`cat temp/versionstring.txt`
    - name: MacOS Publish
      run: |
        suaws s3 rm s3://openbci-gui/${GITHUB_REF}/latest  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
        aws s3 cp $TRAVIS_BUILD_DIR/. s3://openbci-gui/${GITHUB_REF}/${GUI_VERSION_STRING}_${GUI_COMMIT_TIME}  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
        aws s3 cp $TRAVIS_BUILD_DIR/. s3://openbci-gui/${GITHUB_REF}/latest  --recursive --exclude "*" --include "openbcigui_*_macosx.dmg"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}